 IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_~TABLENAME~_~COLUMNNAME~]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[~TABLENAME~] ADD  CONSTRAINT [DF_~TABLENAME~_~COLUMNNAME~]  DEFAULT ((~DEFAULTVALUE~)) FOR [~COLUMNNAME~]
END