IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[~TABLENAME~]') AND name = N'IX_~TABLENAME~')
CREATE NONCLUSTERED INDEX [IX_~TABLENAME~] ON [dbo].[Sales] 
(
	--[Created] DESC,
	--[ProductID] ASC
	~INDEXES~
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY] 