SET ANSI_NULLS ON SET QUOTED_IDENTIFIER ON IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[~TABLENAME~]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[~TABLENAME~](~PROPERTIES~~PKCONSTRAINTS~) ON [PRIMARY]
END
