IF NOT EXISTS (SELECT * FROM [~DATABASENAME~].[dbo].[sysobjects] WHERE name='~TABLENAME~' and xtype='U')
BEGIN
    CREATE TABLE [~DATABASENAME~].[dbo].[~TABLENAME~] (
        ~TABLEPROPERTIES~
    )
END
--DROP TABLE IF EXISTS [~DATABASENAME~].[dbo].[~TABLENAME~]
--CREATE TABLE [~DATABASENAME~].[dbo].[~TABLENAME~]
--(
--	TABLEPROPERTIESGOHERE
--)